#!/bin/bash

#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

FILE=$HOSTNAME
ITERS=${1:-1}
SLEEP=${2:-10}

echo "$FILE-`date +%D`" > $FILE

w >> $FILE
for iter in $(seq 2 $ITERS); do
    sleep $SLEEP
    w >> $FILE
done

cat $FILE
rm $FILE
